### ISSUE TITLE
Bug: Named export 'jwtVerify' not found

### ISSUE THREAD

**Issue by dg-robinson** [kinde-oss/kinde-node-express#27]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

I’ve got a pretty simple Node + Express app for handling API endpoints, and I’ve been importing the `jwtVerify` middleware without any problems in v1.0.12 of the package. However, after updating to v1.2+ my app no longer builds with this error:

```
import { jwtVerify } from '@kinde-oss/kinde-node-express';
         ^^^^^^^^^
SyntaxError: Named export 'jwtVerify' not found. The requested module '@kinde-oss/kinde-node-express' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@kinde-oss/kinde-node-express';
const { jwtVerify } = pkg;
```

So, I’ve tried what it suggests but then I get this error:

```
(node:13928) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/davidrobinson/Developer/deb-wizard-server/node_modules/@kinde-oss/kinde-node-express/dist/index.js:1
import { getInternalClient, setupInternalClient } from './setup';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

I’ve looked at the documentation, and can see you’re using `require` rather than `import`, but then I get this error:
```
const { jwtVerify } = require('@kinde-oss/kinde-node-express');
                      ^

ReferenceError: require is not defined in ES module scope, you can use import instead
```

I’m using .mjs file extensions throughout. I’ve tried renaming them to .js and setting `”type”: “module”` in my package.json instead, but I just get the second error again. I can see the package is outputting both ESM and CJS, and I’d prefer not to have to rewrite my app to use CJS throughout. Any idea what I might be doing wrong, or another way I can fix this?

### Library URL

https://github.com/kinde-oss/kinde-node-express

### Library version

1.4.0

### Operating system(s)

macOS

### Operating system version(s)

macOS Sonoma 14.4.1

### Further environment details

Node.js v20.13.1

**Comment by DanielRivers** [comment]
@dg-robinson I have added back in, however this will likely be removed in later release in favour of `https://github.com/kinde-oss/jwt-validator` in the future

**Comment by dg-robinson** [comment]
@DanielRivers I just tried updating to 1.4.1 but I'm still getting the same issue. It looks like #29 is the same issue, but with a different import. It looks like it's trying to use the CJS output, even though we're trying to use ESM.
