### ISSUE TITLE
Bug: Not compatible with Typescript

### ISSUE THREAD

**Issue by vitorbarbosa19** [kinde-oss/kinde-node-express#5]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

The library is not compatible with Typescript, nor does it include a type declaration file (.d.ts).

As soon as the library is imported the following error occurs:

```
Could not find a declaration file for module '@kinde-oss/kinde-node-express'. '...' implicitly has an 'any' type.
  Try `npm i --save-dev @types/kinde-oss__kinde-node-express` if it exists or add a new declaration (.d.ts) file containing `declare module '@kinde-oss/kinde-node-express';` ts(7016)
```

### Library URL

https://github.com/kinde-oss/kinde-node-express

### Library version

1.0.12

### Operating system(s)

macOS

### Operating system version(s)

Ventura 13.4.1

### Additional information

I can be reproduced by simply creating any Node project that has Typescript installed as a library and a tsconfig.json file in it.

**Comment by atifcppprogrammer** [comment]
@vitorbarbosa19, this SDK has been migrated to TypeScript now with the required types being shipped along with the package, so this issue should be resolved now. :+1:
